"""add_product_additional_fields

Revision ID: 1b338cba5d2e
Revises: 31130031219d
Create Date: 2025-08-20 22:47:53.603860

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1b338cba5d2e'
down_revision: Union[str, Sequence[str], None] = '31130031219d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('sku', sa.String(length=50), nullable=True))
    op.add_column('products', sa.Column('weight', sa.Float(), server_default='0.0', nullable=True))
    op.add_column('products', sa.Column('dimensions', sa.String(length=50), nullable=True))
    op.create_unique_constraint('uq_products_sku', 'products', ['sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_sku', 'products', type_='unique')
    op.drop_column('products', 'dimensions')
    op.drop_column('products', 'weight')
    op.drop_column('products', 'sku')
    # ### end Alembic commands ###